#!/usr/bin/env bash
# script to install nginx on web server

sudo apt update
sudo apt install nginx -y
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
