#!/usr/bin/env bash
# Bash script that displays To infinity and beyond
# display I am invincible!!!
i=0
while [ $i -lt 3 ];
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
