#!/usr/bin/env bash
# This script gives information about school file

file="/root/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/school"

if [ -e "$file" ]; then
	echo school file exists
	if [ -s "$file" ]; then
		printf "school file is not empty\n"
	else
		printf "school file is empty\n"
	fi
	if [ -f "$file" ]; then
		printf "school is a regular file\n"
	else
		return
	fi
else
	printf "school file does not exist\n"

fi
