#!/usr/bin/env bash
# run as nginx

pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo sed -ie "1 i user nginx;" /etc/nginx/nginx.conf
su nginx service nginx start
